#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory
makeType=${1:-libso}
set -x

wmake $makeType specie
wmake $makeType solid
wmake $makeType thermophysicalFunctions

wmake $makeType basic
wmake $makeType reactionThermo
wmake $makeType laminarFlameSpeed

# Can't build here as chemistryModel depends on RAS/turbulenceModels/compressible
# wmake $makeType chemistryModel
wmake $makeType barotropicCompressibilityModel
wmake $makeType thermalPorousZone

# Depends on basic above
./properties/Allwmake $*

wmake $makeType SLGThermo

# Should be combined with solids&solidMixture
wmake $makeType basicSolidThermo

wmake $makeType radiationModels

# ----------------------------------------------------------------- end-of-file
