#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory
. $WM_PROJECT_DIR/wmake/scripts/AllwmakeArguments

wmakeCheckPwd "$WM_PROJECT_DIR/applications" || {
    echo "Error: Current directory is not \$WM_PROJECT_DIR/applications"
    echo "    The environment variables are inconsistent with the installation."
    echo "    Check the OpenFOAM entries in your dot-files and source them."
    exit 1
}

[ -n "$FOAM_EXT_LIBBIN" ] || {
    echo "Error: FOAM_EXT_LIBBIN not set"
    echo "    Check the OpenFOAM entries in your dot-files and source them."
    exit 1
}

#disable multi-core building for the applications folder
onWin && unset WM_NCOMPPROCS

set -x

wmake all utilities
wmake all solvers

if isMinGW; then
  #since we advise to build these in the wiki, lets just put them here to get built too
  ( set +e; wmake all utilities/mesh/conversion/Optional ; exit 0 ) #ccm26ToFoam - use a containment shell since it depends on license.
  wmake all test/parallel #Test-parallel

  wmakeVerifyExeDependencies utilities || wmake all utilities
  wmakeVerifyExeDependencies solvers || wmake all solvers
  
  ( set +e; wmake all utilities/mesh/conversion/Optional ; exit 0 ) #ccm26ToFoam - use a containment shell since it depends on license.
  wmakeVerifyExeDependencies test/parallel || wmake all test/parallel #Test-parallel
fi

# ----------------------------------------------------------------- end-of-file
