#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

unset COMP_FLAGS LINK_FLAGS


# make (non-shared) object
wmake libo

# ----------------------------------------------------------------- end-of-file
