#!/bin/sh

echo "Moving constant/triSurface/motorBike.stl constant/triSurface/motorBike.orig.stl"
mv constant/triSurface/motorBike.stl constant/triSurface/motorBike.orig.stl
echo "Creating motorBike.stl compatible with Windows filesystem"
cat constant/triSurface/motorBike.orig.stl | sed 's/\(.*\):\(.*\)%/\1_\2_/' | sed 's/\(.*\)%/\1_/' > constant/triSurface/motorBike.stl

# echo "Moving system/snappyHexMeshDict system/snappyHexMeshDict.orig"
# mv system/snappyHexMeshDict system/snappyHexMeshDict.orig
# echo "Creating snappyHexMeshDict references to the motorBike.stl compatible with Windows filesystem"
# cat system/snappyHexMeshDict.orig | sed 's/\(.*\):\(.*\)%/\1_\2_/' | sed 's/\(.*\)%/\1_/' > system/snappyHexMeshDict

echo "Removing originals..."
rm constant/triSurface/motorBike.orig.stl
# rm system/snappyHexMeshDict.orig

echo "The motorBike case is now compatible with the Windows filesystem."
