#!/bin/sh
#------------------------------------------------------------------------------
# License
#    This file is part of blueCAPE's unofficial mingw patches for OpenFOAM.
#    For more information about these patches, visit:
#         http://www.bluecape.com.pt/blueCFD
#
#    OpenFOAM's official site: http://www.openfoam.com
#
#    OpenFOAM is free software: you can redistribute it and/or modify it
#    under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    OpenFOAM is distributed in the hope that it will be useful, but WITHOUT
#    ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
#    FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
#    for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with OpenFOAM.  If not, see <http://www.gnu.org/licenses/>.
#
# Script
#     qhelpgenerator_mod
#
# Description
#     This script adds missing files to the main html folder and adds those
#   files to the qhp file given in $1.
#
#------------------------------------------------------------------------------

cd ..

filelist="`find css -mindepth 1` `find . -maxdepth 1 -name "*.png"`"

cd html

#embed all css files and images
for file in $filelist; do
  sed -i -e 's=\(<file>index.html</file>\)=\1\n      <file>'$file'</file>=' index.qhp
done

#remove the relative patchs for the source code
find . -name "*.html" | while read file; do
    echo "Changing paths in $file"
    sed -i -e 's_href="\.\./\.\./\.\./_href="_' $file
done

#copy the source code files
find ../../../src ../../../applications -name "*.[CH]" | grep -v "lnInclude" | \
while read file; do
  partialpath=${file##../../../}
  relpath=${partialpath%/*}
  mkdir -p "$relpath"
  cp "$file" "$partialpath"
done

#embed the source code files
find src applications | \
while read file; do
  sed -i -e 's=\(<file>index.html</file>\)=\1\n      <file>'$file'</file>=' index.qhp
done

#run the real qhelpgenerator
qhelpgenerator $@
