#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory
allwmakeOptions='-allow-lib makeType' && . $WM_PROJECT_DIR/wmake/scripts/AllwmakeArguments
set -x

wmake $makeType incompressible
if onWin; then

#First build them in static form
wmake lib twoPhaseInterfaceProperties
wmake lib interfaceProperties

#Then build libtwoPhaseInterfaceProperties in dynamic
rm $FOAM_LIBBIN/libtwoPhaseInterfaceProperties.*
wmake $makeType twoPhaseInterfaceProperties

#Then build libinterfaceProperties in dynamic
rm $FOAM_LIBBIN/libinterfaceProperties.*
wmake $makeType interfaceProperties

else

wmake $makeType interfaceProperties
wmake $makeType twoPhaseInterfaceProperties

fi

# wmake $makeType compressible

# ----------------------------------------------------------------- end-of-file
