#!/bin/sh
. $WM_PROJECT_DIR/wmake/scripts/AllwmakeArguments

set -x

if [ -z "$WM_MPLIB" ]; then
    exit 0
fi

wmake decomposePar
wmake reconstructPar
wmake reconstructParMesh
wmake redistributeMeshPar
